In [1]:
import numpy as np

In [27]:
# You are given a space separated list of numbers.
# Your task is to print a reversed NumPy array with the element type float.

a=[1,2, 3, 4, -8, -10]
b=np.array(a,float)
print(b[::-1])

[-10.  -8.   4.   3.   2.   1.]


In [28]:
# You are given a space separated list of nine integers. Your task is to convert this list into a 3X3 NumPy array.

l=[1,2,3,4,5,6,7,8,9]
print(np.reshape(l,(3,3)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
# You are given a NXM integer array matrix with space separated elements ( N= rows and  M= columns).
# Your task is to print the transpose and flatten results.

values=int(input()) #number of elements to be present in an array
N=int(input()) #number of rows
M=int(input()) #number of columns
array = np.arange(values).reshape(N,M)
print('Original array: ',array)
print('transposed array: ',np.transpose(array))
print('flatten array: ',array.flatten())

6
2
3
Original array:  [[0 1 2]
 [3 4 5]]
transposed array:  [[0 3]
 [1 4]
 [2 5]]
flatten array:  [0 1 2 3 4 5]


In [39]:
# You are given two integer arrays of size NXP and MXP (N & M are rows, and P is the column). 
# Your task is to concatenate the arrays along axis 0.

values=int(input()) #number of elements to be present in an array
N=int(input()) #number of rows for 1st array
M=int(input()) #number of rows for 2nd array
P=int(input()) #number of columns
array1 = np.arange(values).reshape(N,P)
print('original array1: ',array1)
array2= np.arange(values).reshape(M,P)
print('original array2: ',array2)
print('concatenated array: ',np.concatenate((array1, array2), axis = 0))

6
2
2
3
original array1:  [[0 1 2]
 [3 4 5]]
original array2:  [[0 1 2]
 [3 4 5]]
concatenated array:  [[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]


In [42]:
# You are given the shape of the array in the form of space-separated integers, 
# each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

print(np.ones((3,3,3)))
print(np.zeros((3,3,3)))


[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [44]:
# Your task is to print an array of size NXM with its main diagonal elements as 1's and 0's everywhere else.
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [52]:
# Your task is to perform the following operations:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print('addition: ',np.add(a, b))
print('subtraction: ',np.subtract(a, b))
print('multiplication: ',np.multiply(a, b))
print('division: ',np.divide(a, b))
print('mod: ',np.mod(a, b))
print('power: ',np.power(a, b))

addition:  [ 6  8 10 12]
subtraction:  [-4 -4 -4 -4]
multiplication:  [ 5 12 21 32]
division:  [0.2        0.33333333 0.42857143 0.5       ]
mod:  [1 2 3 4]
power:  [    1    64  2187 65536]


In [53]:
# You are given a 1-D array, A. Your task is to print the floor,ceil  and rint  of all the elements of .

array=np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print('floor: ',np.floor(array))
print('ceil: ',np.ceil(array))
print('rint: ',np.rint(array))

floor:  [1. 2. 3. 4. 5. 6. 7. 8. 9.]
ceil:  [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
rint:  [ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


In [56]:
# You are given a 2-D array with dimensions NXM.
# Your task is to perform the sum tool over axis 0 and then find the product of that result.

my_array = np.array([ [1, 2], [3, 4] ])
summation = np.sum(my_array, axis = 0)
print('summation: ',summation)
prod = np.prod(summation, axis = 0)
print('product: ',prod)

summation:  [4 6]
product:  24


In [60]:
# You are given a 2-D array with dimensions NXM.
# Your task is to perform the min function over axis  and then find the max of that.

my_array = np.array([ [1, 2], [3, 4] ])
minimum = np.min(my_array, axis = 1)
print('minimum: ',minimum)
maximum = np.max(minimum, axis = 0)
print('maximum: ',maximum)

minimum:  [1 3]
maximum:  3


In [62]:
# You are given a 2-D array of size NXM.
# Your task is to find:

# The mean along axis 1 
# The var along axis 0
# The std along axis NONE


my_array = np.array([ [1, 2], [3, 4] ])
print('mean: ',np.mean(my_array, axis = 1))  
print('variance: ',np.var(my_array, axis = 0))
print('standar deviation: ',np.std(my_array, axis = None))

mean:  [1.5 3.5]
variance:  [1. 1.]
standar deviation:  1.118033988749895


In [65]:
# You are given two arrays A and B. Both have dimensions of NXM.
# Your task is to compute their matrix product.

A = np.array([ 1, 2 ])
B = np.array([ 3, 4 ])

print('dot product: ',np.dot(A, B))
print('cross product: ',np.cross(A,B))

dot product:  11
cross product:  -2


In [66]:
# You are given two arrays: A and B.
# Your task is to compute their inner and outer product.

A = np.array([ 1, 2 ])
B = np.array([ 3, 4 ])

print('inner: ',np.inner(A, B))
print('outer: ',np.outer(A,B))

inner:  11
outer:  [[3 4]
 [6 8]]


In [68]:
# You are given the coefficients of a polynomial P.
# Your task is to find the value of  at point x.
print(np.polyval([1.1, 2, 3],0))

3.0


In [72]:
# You are given a square matrix A with dimensions NXM. Your task is to find the determinant. 
# Note: Round the answer to 2 places after the decimal.



determinant = np.linalg.det([[1.1 , 1.1], [1.1, 1.1]])
print(round(determinant,1))

0.0
